/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-application-conventions")
    id("org.openjfx.javafxplugin") version "0.1.0"
}

javafx {
    version = "21"
    modules = listOf("javafx.controls", "javafx.graphics")
}

dependencies {
    testImplementation("org.junit.jupiter:junit-jupiter:5.11.0")
    implementation("org.apache.commons:commons-text")
    implementation(project(":utilities"))

    implementation("org.slf4j:slf4j-api:2.0.13")
    implementation("ch.qos.logback:logback-classic:1.5.6")
    implementation("com.microsoft.onnxruntime:onnxruntime:1.27.0")
    implementation("com.fazecast:jSerialComm:2.11.0")
    implementation("org.openpnp:opencv:4.9.0-0")
}

repositories {
    mavenCentral()
}

application {
    // Define the main class for the application.
    mainClass = "cc.briem.swift.App"
}
